In [1]:
import sys
sys.path.append('..')  # Sube un nivel
from utils import *
from scipy.stats import mannwhitneyu

In [2]:
df_imputed = pd.read_csv(CFG.path_df_imputed_corrected)
print(df_imputed.columns)
print(f"Dataset shape: {df_imputed.shape}")
df_imputed.columns = clean_feature_names(df_imputed.columns)
print(f"\nColumns: {list(df_imputed.columns)}")
df_imputed.tail()

Index(['Plant_Height (cm)', 'Chlorophyll (SPAD)', 'Number of Flowers',
       'Number of Harvested Fruits', 'Weight of Harvested Fruits (Kg)',
       'Fruit Height (mm)', 'Sap pH', 'Sap K (ppm)', 'Sap Ca (ppm)',
       'Sap Na (ppm)', 'Sap NO3 (ppm)', 'Sap Conductivity (mS/cm)',
       'Soil pH Horiba', 'Soil K Horiba (ppm)', 'Soil Ca Horiba (ppm)',
       'Soil Na Horiba (ppm)', 'Soil NO3 Horiba (ppm)',
       'Soil Conductivity Horiba (mS/cm)', 'Fruit Diameter (mm)',
       '7in1_Ph[pH]', '7in1_Moisture[%RH]', '7in1_S_Temperature[C]',
       'Air_sensor_Temperature[C]', 'Air_sensor_Humidity[%RH]',
       '7in1_Conductivity[mS/cm]', 'Pynamometer_Radiation[W/m2]', 'Nitrogen',
       'Phosphorus', 'Potassium', 'Year', 'Month', 'Day', 'Treatment_Num'],
      dtype='object')
Dataset shape: (2262, 33)

Columns: ['Plant_Height (cm)', 'Chlorophyll (SPAD)', 'Number of Flowers', 'Number of Harvested Fruits', 'Weight of Harvested Fruits (Kg)', 'Fruit Height (mm)', 'Sap pH', 'Sap K (ppm)', 'Sap Ca (ppm)', 'Sap Na (ppm)', 'Sap NO3 (ppm)', 'Sap Conductivity (mS/cm)', 'Soil pH Horiba', 'Soil K Horiba (ppm)', 'Soil Ca Horiba (ppm)', 'Soil Na Horiba (ppm)', 'Soil NO3 Horiba (ppm)', 'Soil Conductivity Horiba (mS/cm)', 'Fruit Diameter (mm)', '7in1_Ph(pH)', '7in1_Moisture(%RH)', '7in1_S_Temperature(C)', 'Air_sensor_Temperature(C)', 'Air_sensor_Humidity(%RH)', '7in1_Conductivity(mS/cm)', 'Pynamometer_Radiation(W/m2)', 'Nitrogen', 'Phosphorus', 'Potassium', 'Year', 'Month', 'Day', 'Treatment_Num']

,Plant_Height (cm),Chlorophyll (SPAD),Number of Flowers,Number of Harvested Fruits,Weight of Harvested Fruits (Kg),Fruit Height (mm),Sap pH,Sap K (ppm),Sap Ca (ppm),Sap Na (ppm),...,Air_sensor_Humidity(%RH),7in1_Conductivity(mS/cm),Pynamometer_Radiation(W/m2),Nitrogen,Phosphorus,Potassium,Year,Month,Day,Treatment_Num
2257,168.05,57.72,20.1,1.0,0.180,70.3,5.619,3880.0,383.3,55.20,...,74.16,0.0940,153.9,2.0,2.0,2.0,2024.0,12.0,4.0,27.0
2258,152.80,56.59,20.3,7.0,0.706,60.7,5.558,3200.0,410.0,47.45,...,67.29,0.2157,290.5,2.0,2.0,2.0,2024.0,12.0,4.0,27.0
2259,151.50,61.13,16.9,6.0,0.829,70.2,5.504,3430.0,219.0,54.80,...,63.30,0.0280,269.0,0.0,0.0,1.0,2024.0,12.0,4.0,4.0
2260,82.60,46.24,15.7,2.0,0.174,50.7,5.629,3390.0,213.6,54.60,...,52.33,0.2627,721.3,0.0,0.0,1.0,2024.0,12.0,4.0,4.0
2261,174.40,61.40,18.6,1.0,0.150,70.1,5.654,3350.0,228.6,49.20,...,65.71,0.0764,217.3,0.0,0.0,1.0,2024.0,12.0,4.0,4.0

In [3]:
# with open(CFG.treat_quantiles_path, 'r') as f:
#     treatments_quantile_unified = json.load(f)

In [4]:
df_imputed, df_imputed['target'] = codificar_clase_cuartiles(df_imputed, filter_data=True, CFG=CFG)

## Cargar JSON con mejores variables halladas

In [5]:
CFG.Root = "../" 
json_best_variables = Rf"{CFG.Root}\Resultados\classification_exclude_prod\most_frequent_variables_80.json"
# TODO: Checkear que la ruta existe. Se debió ejecutar el modelo de train anterior.
#list_best_vars = read_best_variables(json_best_variables)

In [6]:
#
list_best_vars = ['Sap Na (ppm)', 
                  'Sap NO3 (ppm)', # solo en cuartiles
                   'Sap Ca (ppm)', #NPK
                     'Sap Conductivity (mS/cm)',#NK
                     'Soil pH Horiba', #PK
                  'Chlorophyll (SPAD)', #N
                  'Soil Ca Horiba (ppm)', #P
                  'Sap K (ppm)' #K
                    ]

In [7]:
df_imputed[df_imputed['target'] == 1]

,Plant_Height (cm),Chlorophyll (SPAD),Number of Flowers,Number of Harvested Fruits,Weight of Harvested Fruits (Kg),Fruit Height (mm),Sap pH,Sap K (ppm),Sap Ca (ppm),Sap Na (ppm),...,7in1_Conductivity(mS/cm),Pynamometer_Radiation(W/m2),Nitrogen,Phosphorus,Potassium,Year,Month,Day,Treatment_Num,target
5,18.5,43.30,20.0,0.0,0.000,0.0,5.5500,4030.0,268.9,66.80,...,0.3940,404.0,1.0,0.0,1.0,2024.0,7.0,30.0,13.0,1
6,13.0,39.80,11.0,0.0,0.000,0.0,5.5975,3455.0,310.0,45.30,...,0.1720,469.0,2.0,0.0,1.0,2024.0,7.0,30.0,22.0,1
9,23.0,40.30,21.0,0.0,0.000,0.0,5.6160,4145.0,429.1,59.40,...,0.3860,412.0,1.0,2.0,0.0,2024.0,7.0,30.0,12.0,1
14,17.5,37.00,9.8,0.0,0.000,0.0,5.6660,3960.0,118.7,60.25,...,0.5550,353.0,0.0,1.0,2.0,2024.0,7.0,30.0,7.0,1
15,19.0,35.70,11.1,0.0,0.000,0.0,5.5600,3340.0,174.3,54.05,...,0.5690,285.0,0.0,2.0,0.0,2024.0,7.0,30.0,3.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2212,158.3,50.61,13.9,0.0,0.000,0.0,5.8700,3500.0,219.0,51.60,...,0.1432,327.9,0.0,1.0,2.0,2024.0,12.0,4.0,7.0,1
2213,158.3,50.61,13.9,0.0,0.000,0.0,5.8700,3500.0,219.0,51.60,...,0.1432,327.9,0.0,1.0,2.0,2024.0,12.0,4.0,7.0,1
2232,128.4,55.77,8.1,0.0,0.000,0.0,5.7185,3300.0,118.0,41.40,...,0.0580,267.0,2.0,1.0,2.0,2024.0,12.0,4.0,25.0,1
2233,161.0,58.00,9.7,3.0,0.273,50.5,5.8000,3380.0,127.1,42.90,...,0.1461,288.4,2.0,1.0,2.0,2024.0,12.0,4.0,25.0,1
2234,151.4,57.56,8.8,0.0,0.000,0.0,5.7685,3315.0,125.7,40.10,...,0.1175,264.2,2.0,1.0,2.0,2024.0,12.0,4.0,25.0,1

In [8]:
for var in list_best_vars:
    group1 = df_imputed[df_imputed['target'] == 1][var]
    group2 = df_imputed[df_imputed['target'] == 4][var]
    
    stat, p = mannwhitneyu(group1, group2, alternative='two-sided')
    print(f"Variable: {var}, Mann-Whitney U statistic: {stat}, p-value: {p:.6f}")

Variable: Sap Na (ppm), Mann-Whitney U statistic: 217345.0, p-value: 0.000000
Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 165843.0, p-value: 0.005459
Variable: Sap Ca (ppm), Mann-Whitney U statistic: 170837.0, p-value: 0.050478
Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 206570.5, p-value: 0.000085
Variable: Soil pH Horiba, Mann-Whitney U statistic: 135197.0, p-value: 0.000000
Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 159565.0, p-value: 0.000137
Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 221306.0, p-value: 0.000000
Variable: Sap K (ppm), Mann-Whitney U statistic: 210403.0, p-value: 0.000005

In [9]:
df_imputed['Fecha'] = pd.to_datetime(df_imputed[['Year', 'Month', 'Day']])
results = []
alerta_generada = False
date_cosecha = pd.to_datetime("2024-10-02")

dict_alertas ={}
for var in list_best_vars:
    n_semana = 0
    n_semana_cosecha = 0
    n_semana_alerta = 0
    alerta_generada = False
    for date in df_imputed['Fecha'].unique():
        group1 = df_imputed[(df_imputed['target'] == 1) & (df_imputed['Fecha'] == date)][var]
        group2 = df_imputed[(df_imputed['target'] == 4) & (df_imputed['Fecha'] == date)][var]
        
        if len(group1) > 0 and len(group2) > 0:
            stat, p = mannwhitneyu(group1, group2, alternative='two-sided')
            results.append({'Fecha': date, 'Variable': var, 'U_statistic': stat, 'p_value': p, 'n_group1': len(group1), 'n_group2': len(group2)})
            print(f"Date: {date}, Variable: {var}, Mann-Whitney U statistic: {stat}, p-value: {p:.6f}")
        else:
            print(f"Date: {date}, Variable: {var}, Not enough data for one of the groups.")
        n_semana += 1
        if date == date_cosecha:
            n_semana_cosecha = n_semana
        if p < 0.05 and not alerta_generada:
            print(f"ALERTA: {var} ")
            alerta_generada = True
            n_semana_alerta = n_semana
    print(f"Alerta de {var} - Semana {n_semana_alerta - n_semana_cosecha}")
    dict_alertas[var] = n_semana_alerta - n_semana_cosecha
    
df_results = pd.DataFrame(results)
# df_results.to_csv('mann_whitney_test.csv', index=False)
# df_results.to_excel('mann_w-u-test2.xlsx', index=False)

print(dict_alertas)
#converit dict_alertas a dataframe
df_alertas = pd.DataFrame(list(dict_alertas.items()), columns=['Variable', 'Semanas_antes_cosecha'])
df_alertas.to_csv('alertas_variables.csv', index=False)

print(f"\nResultados guardados en mann_whitney_test.csv. Total de pruebas: {len(df_results)}")
df_results.head()

Date: 2024-07-30 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 50.0, p-value: 0.064957
Date: 2024-08-06 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 199.0, p-value: 0.007877
ALERTA: Sap Na (ppm)
Date: 2024-08-14 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 186.5, p-value: 0.028804
Date: 2024-08-21 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 160.5, p-value: 0.227544
Date: 2024-08-27 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 188.5, p-value: 0.023713
Date: 2024-09-04 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 145.0, p-value: 0.533767
Date: 2024-09-11 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 174.5, p-value: 0.488031
Date: 2024-09-17 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 36.5, p-value: 1.000000
Date: 2024-09-25 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 73.5, p-value: 0.411092
Date: 2024-10-02 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 1209.0, p-value: 0.678664
Date: 2024-10-09 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 1272.0, p-value: 0.285412
Date: 2024-10-16 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 1313.0, p-value: 0.239470
Date: 2024-10-23 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 1486.5, p-value: 0.014380
Date: 2024-10-30 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 1683.5, p-value: 0.000100
Date: 2024-11-06 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 1395.5, p-value: 0.074952
Date: 2024-11-13 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 1451.0, p-value: 0.028712
Date: 2024-11-20 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 1246.0, p-value: 0.493085
Date: 2024-11-27 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 1285.5, p-value: 0.329701
Date: 2024-12-04 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 1130.0, p-value: 0.874806
Alerta de Sap Na (ppm) - Semana -8
Date: 2024-07-30 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 28.0, p-value: 0.720901
Date: 2024-08-06 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 85.0, p-value: 0.109172
Date: 2024-08-14 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 64.0, p-value: 0.016700
ALERTA: Sap NO3 (ppm)
Date: 2024-08-21 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 90.0, p-value: 0.157291
Date: 2024-08-27 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 116.5, p-value: 0.678284
Date: 2024-09-04 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 83.5, p-value: 0.096856
Date: 2024-09-11 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 112.5, p-value: 0.186646
Date: 2024-09-17 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 23.5, p-value: 0.245592
Date: 2024-09-25 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 58.0, p-value: 0.895220
Date: 2024-10-02 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 825.0, p-value: 0.016692
Date: 2024-10-09 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 1016.5, p-value: 0.408652
Date: 2024-10-16 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 907.5, p-value: 0.073771
Date: 2024-10-23 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 1147.0, p-value: 0.973695
Date: 2024-10-30 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 1002.0, p-value: 0.273288
Date: 2024-11-06 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 1114.0, p-value: 0.783476
Date: 2024-11-13 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 1055.0, p-value: 0.479478
Date: 2024-11-20 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 1202.0, p-value: 0.716809
Date: 2024-11-27 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 1116.0, p-value: 0.794747
Date: 2024-12-04 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 1240.5, p-value: 0.519002
Alerta de Sap NO3 (ppm) - Semana -7
Date: 2024-07-30 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 16.0, p-value: 0.104895
Date: 2024-08-06 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 95.0, p-value: 0.220574
Date: 2024-08-14 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 118.0, p-value: 0.720310
Date: 2024-08-21 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 103.0, p-value: 0.355810
Date: 2024-08-27 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 122.0, p-value: 0.835769
Date: 2024-09-04 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 81.5, p-value: 0.082917
Date: 2024-09-11 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 164.5, p-value: 0.716545
Date: 2024-09-17 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 38.0, p-value: 0.885024
Date: 2024-09-25 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 66.0, p-value: 0.742174
Date: 2024-10-02 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 854.5, p-value: 0.029479
ALERTA: Sap Ca (ppm)
Date: 2024-10-09 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 1162.0, p-value: 0.803078
Date: 2024-10-16 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 1369.5, p-value: 0.111808
Date: 2024-10-23 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 1127.0, p-value: 0.857522
Date: 2024-10-30 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 1236.0, p-value: 0.540620
Date: 2024-11-06 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 1167.5, p-value: 0.912476
Date: 2024-11-13 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 1023.5, p-value: 0.348266
Date: 2024-11-20 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 975.0, p-value: 0.195884
Date: 2024-11-27 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 1078.0, p-value: 0.590156
Date: 2024-12-04 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 845.0, p-value: 0.024703
Alerta de Sap Ca (ppm) - Semana 0
Date: 2024-07-30 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 36.0, p-value: 0.720901
Date: 2024-08-06 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 151.0, p-value: 0.396438
Date: 2024-08-14 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 163.0, p-value: 0.193509
Date: 2024-08-21 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 122.0, p-value: 0.835784
Date: 2024-08-27 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 164.0, p-value: 0.180911
Date: 2024-09-04 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 107.0, p-value: 0.439746
Date: 2024-09-11 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 200.0, p-value: 0.124850
Date: 2024-09-17 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 32.0, p-value: 0.742986
Date: 2024-09-25 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 68.0, p-value: 0.645764
Date: 2024-10-02 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 965.0, p-value: 0.171609
Date: 2024-10-09 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 1113.0, p-value: 0.914047
Date: 2024-10-16 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 1407.0, p-value: 0.062195
Date: 2024-10-23 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 1397.5, p-value: 0.072606
Date: 2024-10-30 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 1520.0, p-value: 0.007082
ALERTA: Sap Conductivity (mS/cm)
Date: 2024-11-06 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 1508.5, p-value: 0.009090
Date: 2024-11-13 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 1310.0, p-value: 0.248447
Date: 2024-11-20 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 1264.0, p-value: 0.413900
Date: 2024-11-27 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 1332.0, p-value: 0.188400
Date: 2024-12-04 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 1191.0, p-value: 0.777844
Alerta de Sap Conductivity (mS/cm) - Semana 4
Date: 2024-07-30 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 42.0, p-value: 0.292162
Date: 2024-08-06 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 86.5, p-value: 0.121636
Date: 2024-08-14 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 122.5, p-value: 0.850352
Date: 2024-08-21 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 124.0, p-value: 0.894901
Date: 2024-08-27 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 140.0, p-value: 0.664708
Date: 2024-09-04 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 88.0, p-value: 0.135952
Date: 2024-09-11 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 133.0, p-value: 0.519662
Date: 2024-09-17 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 40.5, p-value: 0.698014
Date: 2024-09-25 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 83.5, p-value: 0.139328
Date: 2024-10-02 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 991.0, p-value: 0.239391
Date: 2024-10-09 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 666.5, p-value: 0.000600
ALERTA: Soil pH Horiba
Date: 2024-10-16 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 798.5, p-value: 0.009686
Date: 2024-10-23 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 1107.5, p-value: 0.747123
Date: 2024-10-30 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 712.0, p-value: 0.001279
Date: 2024-11-06 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 584.0, p-value: 0.000032
Date: 2024-11-13 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 333.0, p-value: 0.000000
Date: 2024-11-20 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 883.5, p-value: 0.049531
Date: 2024-11-27 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 788.5, p-value: 0.007813
Date: 2024-12-04 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 874.5, p-value: 0.042346
Alerta de Soil pH Horiba - Semana 1
Date: 2024-07-30 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 33.0, p-value: 0.958091
Date: 2024-08-06 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 97.5, p-value: 0.258108
Date: 2024-08-14 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 146.5, p-value: 0.497439
Date: 2024-08-21 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 133.0, p-value: 0.865276
Date: 2024-08-27 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 73.0, p-value: 0.039971
ALERTA: Chlorophyll (SPAD)
Date: 2024-09-04 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 105.5, p-value: 0.406887
Date: 2024-09-11 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 145.5, p-value: 0.817275
Date: 2024-09-17 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 53.0, p-value: 0.113945
Date: 2024-09-25 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 39.0, p-value: 0.167785
Date: 2024-10-02 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 734.0, p-value: 0.002211
Date: 2024-10-09 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 889.5, p-value: 0.076454
Date: 2024-10-16 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 1005.5, p-value: 0.284686
Date: 2024-10-23 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 926.0, p-value: 0.098449
Date: 2024-10-30 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 1007.0, p-value: 0.289662
Date: 2024-11-06 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 899.5, p-value: 0.064807
Date: 2024-11-13 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 1186.5, p-value: 0.803248
Date: 2024-11-20 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 1229.0, p-value: 0.575085
Date: 2024-11-27 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 914.5, p-value: 0.082440
Date: 2024-12-04 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 1021.5, p-value: 0.340769
Alerta de Chlorophyll (SPAD) - Semana -5
Date: 2024-07-30 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 46.0, p-value: 0.160528
Date: 2024-08-06 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 158.0, p-value: 0.266170
Date: 2024-08-14 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 142.0, p-value: 0.610892
Date: 2024-08-21 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 125.0, p-value: 0.924926
Date: 2024-08-27 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 132.5, p-value: 0.880158
Date: 2024-09-04 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 81.0, p-value: 0.079544
Date: 2024-09-11 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 237.0, p-value: 0.005849
ALERTA: Soil Ca Horiba (ppm)
Date: 2024-09-17 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 23.0, p-value: 0.235870
Date: 2024-09-25 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 67.0, p-value: 0.693588
Date: 2024-10-02 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 1252.5, p-value: 0.463532
Date: 2024-10-09 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 1384.5, p-value: 0.056691
Date: 2024-10-16 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 1356.5, p-value: 0.134912
Date: 2024-10-23 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 1411.5, p-value: 0.057702
Date: 2024-10-30 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 1520.5, p-value: 0.006996
Date: 2024-11-06 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 1467.0, p-value: 0.021188
Date: 2024-11-13 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 1438.5, p-value: 0.036105
Date: 2024-11-20 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 1445.5, p-value: 0.031788
Date: 2024-11-27 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 1745.0, p-value: 0.000014
Date: 2024-12-04 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 1536.0, p-value: 0.004947
Alerta de Soil Ca Horiba (ppm) - Semana -3
Date: 2024-07-30 00:00:00, Variable: Sap K (ppm), Mann-Whitney U statistic: 44.0, p-value: 0.225777
Date: 2024-08-06 00:00:00, Variable: Sap K (ppm), Mann-Whitney U statistic: 167.5, p-value: 0.141415
Date: 2024-08-14 00:00:00, Variable: Sap K (ppm), Mann-Whitney U statistic: 125.0, p-value: 0.924878
Date: 2024-08-21 00:00:00, Variable: Sap K (ppm), Mann-Whitney U statistic: 147.0, p-value: 0.485049
Date: 2024-08-27 00:00:00, Variable: Sap K (ppm), Mann-Whitney U statistic: 151.0, p-value: 0.396004
Date: 2024-09-04 00:00:00, Variable: Sap K (ppm), Mann-Whitney U statistic: 154.0, p-value: 0.335809
Date: 2024-09-11 00:00:00, Variable: Sap K (ppm), Mann-Whitney U statistic: 177.0, p-value: 0.437719
Date: 2024-09-17 00:00:00, Variable: Sap K (ppm), Mann-Whitney U statistic: 31.5, p-value: 0.697116
Date: 2024-09-25 00:00:00, Variable: Sap K (ppm), Mann-Whitney U statistic: 89.0, p-value: 0.064826
Date: 2024-10-02 00:00:00, Variable: Sap K (ppm), Mann-Whitney U statistic: 984.5, p-value: 0.220689
Date: 2024-10-09 00:00:00, Variable: Sap K (ppm), Mann-Whitney U statistic: 1130.0, p-value: 0.991088
Date: 2024-10-16 00:00:00, Variable: Sap K (ppm), Mann-Whitney U statistic: 1161.5, p-value: 0.947404
Date: 2024-10-23 00:00:00, Variable: Sap K (ppm), Mann-Whitney U statistic: 1415.0, p-value: 0.054380
Date: 2024-10-30 00:00:00, Variable: Sap K (ppm), Mann-Whitney U statistic: 1532.5, p-value: 0.005353
ALERTA: Sap K (ppm)
Date: 2024-11-06 00:00:00, Variable: Sap K (ppm), Mann-Whitney U statistic: 1492.0, p-value: 0.012827
Date: 2024-11-13 00:00:00, Variable: Sap K (ppm), Mann-Whitney U statistic: 1299.5, p-value: 0.281289
Date: 2024-11-20 00:00:00, Variable: Sap K (ppm), Mann-Whitney U statistic: 1209.0, p-value: 0.678758
Date: 2024-11-27 00:00:00, Variable: Sap K (ppm), Mann-Whitney U statistic: 1328.5, p-value: 0.197022
Date: 2024-12-04 00:00:00, Variable: Sap K (ppm), Mann-Whitney U statistic: 1449.5, p-value: 0.029491
Alerta de Sap K (ppm) - Semana 4
{'Sap Na (ppm)': -8, 'Sap NO3 (ppm)': -7, 'Sap Ca (ppm)': 0, 'Sap Conductivity (mS/cm)': 4, 'Soil pH Horiba': 1, 'Chlorophyll (SPAD)': -5, 'Soil Ca Horiba (ppm)': -3, 'Sap K (ppm)': 4}

Resultados guardados en mann_whitney_test.csv. Total de pruebas: 152

       Fecha      Variable  U_statistic   p_value  n_group1  n_group2
0 2024-07-30  Sap Na (ppm)         50.0  0.064957         8         8
1 2024-08-06  Sap Na (ppm)        199.0  0.007877        16        16
2 2024-08-14  Sap Na (ppm)        186.5  0.028804        16        16
3 2024-08-21  Sap Na (ppm)        160.5  0.227544        16        16
4 2024-08-27  Sap Na (ppm)        188.5  0.023713        16        16