In [1]:
import sys
sys.path.append('..')  # Sube un nivel
from utils import *
from scipy.stats import mannwhitneyu

In [2]:
df_imputed = pd.read_csv(CFG.path_df_imputed_corrected)
print(df_imputed.columns)
print(f"Dataset shape: {df_imputed.shape}")
df_imputed.columns = clean_feature_names(df_imputed.columns)
print(f"\nColumns: {list(df_imputed.columns)}")
df_imputed.tail()

Index(['Plant_Height (cm)', 'Chlorophyll (SPAD)', 'Number of Flowers',
       'Number of Harvested Fruits', 'Weight of Harvested Fruits (Kg)',
       'Fruit Height (mm)', 'Sap pH', 'Sap K (ppm)', 'Sap Ca (ppm)',
       'Sap Na (ppm)', 'Sap NO3 (ppm)', 'Sap Conductivity (mS/cm)',
       'Soil pH Horiba', 'Soil K Horiba (ppm)', 'Soil Ca Horiba (ppm)',
       'Soil Na Horiba (ppm)', 'Soil NO3 Horiba (ppm)',
       'Soil Conductivity Horiba (mS/cm)', 'Fruit Diameter (mm)',
       '7in1_Ph[pH]', '7in1_Moisture[%RH]', '7in1_S_Temperature[C]',
       'Air_sensor_Temperature[C]', 'Air_sensor_Humidity[%RH]',
       '7in1_Conductivity[mS/cm]', 'Pynamometer_Radiation[W/m2]', 'Nitrogen',
       'Phosphorus', 'Potassium', 'Year', 'Month', 'Day', 'Treatment_Num'],
      dtype='object')
Dataset shape: (2292, 33)

Columns: ['Plant_Height (cm)', 'Chlorophyll (SPAD)', 'Number of Flowers', 'Number of Harvested Fruits', 'Weight of Harvested Fruits (Kg)', 'Fruit Height (mm)', 'Sap pH', 'Sap K (ppm)', 'Sap Ca (ppm)', 'Sap Na (ppm)', 'Sap NO3 (ppm)', 'Sap Conductivity (mS/cm)', 'Soil pH Horiba', 'Soil K Horiba (ppm)', 'Soil Ca Horiba (ppm)', 'Soil Na Horiba (ppm)', 'Soil NO3 Horiba (ppm)', 'Soil Conductivity Horiba (mS/cm)', 'Fruit Diameter (mm)', '7in1_Ph(pH)', '7in1_Moisture(%RH)', '7in1_S_Temperature(C)', 'Air_sensor_Temperature(C)', 'Air_sensor_Humidity(%RH)', '7in1_Conductivity(mS/cm)', 'Pynamometer_Radiation(W/m2)', 'Nitrogen', 'Phosphorus', 'Potassium', 'Year', 'Month', 'Day', 'Treatment_Num']

,Plant_Height (cm),Chlorophyll (SPAD),Number of Flowers,Number of Harvested Fruits,Weight of Harvested Fruits (Kg),Fruit Height (mm),Sap pH,Sap K (ppm),Sap Ca (ppm),Sap Na (ppm),...,Air_sensor_Humidity(%RH),7in1_Conductivity(mS/cm),Pynamometer_Radiation(W/m2),Nitrogen,Phosphorus,Potassium,Year,Month,Day,Treatment_Num
2287,171.0,57.33,23.6,1.0,0.180,70.3,5.438,3580.0,385.4,49.60,...,79.64,0.1307,271.1,2.0,2.0,2.0,2024.0,12.0,4.0,27.0
2288,167.2,57.19,23.4,7.0,0.706,60.7,5.438,3230.0,263.2,49.70,...,68.08,0.1242,262.7,2.0,2.0,2.0,2024.0,12.0,4.0,27.0
2289,136.6,60.03,14.1,6.0,0.829,70.2,5.506,3490.0,226.0,57.10,...,63.30,0.0280,269.0,0.0,0.0,1.0,2024.0,12.0,4.0,4.0
2290,64.6,50.57,7.7,2.0,0.174,50.7,5.667,3330.0,223.6,50.35,...,53.07,0.2098,347.2,0.0,0.0,1.0,2024.0,12.0,4.0,4.0
2291,180.5,59.77,19.7,1.0,0.150,70.1,5.594,3480.0,181.2,57.40,...,64.70,0.0144,263.5,0.0,0.0,1.0,2024.0,12.0,4.0,4.0

In [3]:
# with open(CFG.treat_quantiles_path, 'r') as f:
#     treatments_quantile_unified = json.load(f)

In [4]:
df_imputed, df_imputed['target'] = codificar_clase_cuartiles(df_imputed, filter_data=True, CFG=CFG)

In [5]:
CFG.Root = "../"
json_best_variables = Rf"{CFG.Root}\Resultados\classification_exclude_prod\most_frequent_variables_80.json"
# TODO: Checkear que la ruta existe. Se debió ejecutar el modelo de train anterior.
list_best_vars = read_best_variables(json_best_variables)

In [6]:
list_best_vars

['Soil pH Horiba',
 'Sap Na (ppm)',
 'Chlorophyll (SPAD)',
 'Sap Ca (ppm)',
 'Sap NO3 (ppm)',
 '7in1_S_Temperature(C)',
 'Sap Conductivity (mS/cm)',
 'Soil Ca Horiba (ppm)',
 'Air_sensor_Humidity(%RH)',
 'Soil Na Horiba (ppm)',
 '7in1_Ph(pH)',
 'Sap pH']

In [7]:
for var in list_best_vars:
    group1 = df_imputed[df_imputed['target'] == 0][var]
    group2 = df_imputed[df_imputed['target'] == 1][var]
    
    stat, p = mannwhitneyu(group1, group2, alternative='two-sided')
    print(f"Variable: {var}, Mann-Whitney U statistic: {stat}, p-value: {p:.6f}")

Variable: Soil pH Horiba, Mann-Whitney U statistic: 139392.5, p-value: 0.000000
Variable: Sap Na (ppm), Mann-Whitney U statistic: 213350.0, p-value: 0.000031
Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 144999.5, p-value: 0.000000
Variable: Sap Ca (ppm), Mann-Whitney U statistic: 194543.0, p-value: 0.260613
Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 169161.0, p-value: 0.002932
Variable: 7in1_S_Temperature(C), Mann-Whitney U statistic: 236400.0, p-value: 0.000000
Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 209563.5, p-value: 0.000384
Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 225147.0, p-value: 0.000000
Variable: Air_sensor_Humidity(%RH), Mann-Whitney U statistic: 151908.0, p-value: 0.000000
Variable: Soil Na Horiba (ppm), Mann-Whitney U statistic: 211078.5, p-value: 0.000147
Variable: 7in1_Ph(pH), Mann-Whitney U statistic: 171492.5, p-value: 0.009371
Variable: Sap pH, Mann-Whitney U statistic: 199108.5, p-value: 0.062534

In [8]:
df_imputed['Fecha'] = pd.to_datetime(df_imputed[['Year', 'Month', 'Day']])
results = []
alerta_generada = False
date_cosecha = pd.to_datetime("2024-10-02")

dict_alertas ={}
for var in list_best_vars:
    n_semana = 0
    n_semana_cosecha = 0
    n_semana_alerta = 0
    alerta_generada = False
    for date in df_imputed['Fecha'].unique():
        group1 = df_imputed[(df_imputed['target'] == 0) & (df_imputed['Fecha'] == date)][var]
        group2 = df_imputed[(df_imputed['target'] == 1) & (df_imputed['Fecha'] == date)][var]
        
        if len(group1) > 0 and len(group2) > 0:
            stat, p = mannwhitneyu(group1, group2, alternative='two-sided')
            results.append({'Fecha': date, 'Variable': var, 'U_statistic': stat, 'p_value': p, 'n_group1': len(group1), 'n_group2': len(group2)})
            print(f"Date: {date}, Variable: {var}, Mann-Whitney U statistic: {stat}, p-value: {p:.6f}")
        else:
            print(f"Date: {date}, Variable: {var}, Not enough data for one of the groups.")
        n_semana += 1
        if date == date_cosecha:
            n_semana_cosecha = n_semana
        if p < 0.05 and not alerta_generada:
            print(f"ALERTA: {var} ")
            alerta_generada = True
            n_semana_alerta = n_semana
    print(f"Alerta de {var} - Semana {n_semana_alerta - n_semana_cosecha}")
    dict_alertas[var] = n_semana_alerta - n_semana_cosecha
    
df_results = pd.DataFrame(results)
df_results.to_csv('mann_whitney_test.csv', index=False)
df_results.to_excel('mann_w-u-test2.xlsx', index=False)

print(dict_alertas)
#converit dict_alertas a dataframe
df_alertas = pd.DataFrame(list(dict_alertas.items()), columns=['Variable', 'Semanas_antes_cosecha'])
df_alertas.to_csv('alertas_variables.csv', index=False)

print(f"\nResultados guardados en mann_whitney_test.csv. Total de pruebas: {len(df_results)}")
df_results.head()

Date: 2024-07-30 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 42.0, p-value: 0.292162
Date: 2024-08-06 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 91.5, p-value: 0.174132
Date: 2024-08-14 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 142.0, p-value: 0.610532
Date: 2024-08-21 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 130.5, p-value: 0.939815
Date: 2024-08-27 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 40.0, p-value: 0.441803
Date: 2024-08-28 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 139.5, p-value: 0.678395
Date: 2024-09-04 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 95.0, p-value: 0.219897
Date: 2024-09-11 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 119.0, p-value: 0.268670
Date: 2024-09-17 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 40.5, p-value: 0.698014
Date: 2024-09-25 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 83.5, p-value: 0.139328
Date: 2024-10-02 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 765.5, p-value: 0.004662
ALERTA: Soil pH Horiba
Date: 2024-10-09 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 766.5, p-value: 0.007203
Date: 2024-10-16 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 876.0, p-value: 0.043498
Date: 2024-10-23 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 1036.5, p-value: 0.399350
Date: 2024-10-30 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 819.0, p-value: 0.014821
Date: 2024-11-06 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 578.0, p-value: 0.000026
Date: 2024-11-13 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 405.0, p-value: 0.000000
Date: 2024-11-20 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 799.0, p-value: 0.009788
Date: 2024-11-27 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 683.0, p-value: 0.000597
Date: 2024-12-04 00:00:00, Variable: Soil pH Horiba, Mann-Whitney U statistic: 828.5, p-value: 0.017931
Alerta de Soil pH Horiba - Semana 0
Date: 2024-07-30 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 49.0, p-value: 0.082896
Date: 2024-08-06 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 171.0, p-value: 0.109107
Date: 2024-08-14 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 185.0, p-value: 0.033187
ALERTA: Sap Na (ppm)
Date: 2024-08-21 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 152.0, p-value: 0.375566
Date: 2024-08-27 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 50.0, p-value: 0.065883
Date: 2024-08-28 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 181.5, p-value: 0.045730
Date: 2024-09-04 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 145.0, p-value: 0.533804
Date: 2024-09-11 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 174.5, p-value: 0.488031
Date: 2024-09-17 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 36.5, p-value: 1.000000
Date: 2024-09-25 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 74.5, p-value: 0.374685
Date: 2024-10-02 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 1087.0, p-value: 0.636338
Date: 2024-10-09 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 1173.0, p-value: 0.740442
Date: 2024-10-16 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 1316.5, p-value: 0.229408
Date: 2024-10-23 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 1386.5, p-value: 0.086371
Date: 2024-10-30 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 1585.0, p-value: 0.001527
Date: 2024-11-06 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 1303.0, p-value: 0.270067
Date: 2024-11-13 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 1417.0, p-value: 0.052590
Date: 2024-11-20 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 1120.5, p-value: 0.820265
Date: 2024-11-27 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 1305.0, p-value: 0.263704
Date: 2024-12-04 00:00:00, Variable: Sap Na (ppm), Mann-Whitney U statistic: 1012.5, p-value: 0.308344
Alerta de Sap Na (ppm) - Semana -8
Date: 2024-07-30 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 33.0, p-value: 0.958091
Date: 2024-08-06 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 101.5, p-value: 0.327041
Date: 2024-08-14 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 165.5, p-value: 0.163093
Date: 2024-08-21 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 141.0, p-value: 0.637252
Date: 2024-08-27 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 22.0, p-value: 0.328205
Date: 2024-08-28 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 54.0, p-value: 0.005599
ALERTA: Chlorophyll (SPAD)
Date: 2024-09-04 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 103.5, p-value: 0.365580
Date: 2024-09-11 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 132.5, p-value: 0.509161
Date: 2024-09-17 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 53.0, p-value: 0.113945
Date: 2024-09-25 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 37.5, p-value: 0.139328
Date: 2024-10-02 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 601.0, p-value: 0.000055
Date: 2024-10-09 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 876.5, p-value: 0.061705
Date: 2024-10-16 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 806.0, p-value: 0.011351
Date: 2024-10-23 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 815.0, p-value: 0.013671
Date: 2024-10-30 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 880.0, p-value: 0.046648
Date: 2024-11-06 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 721.0, p-value: 0.001607
Date: 2024-11-13 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 961.5, p-value: 0.163825
Date: 2024-11-20 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 892.0, p-value: 0.057223
Date: 2024-11-27 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 864.0, p-value: 0.035134
Date: 2024-12-04 00:00:00, Variable: Chlorophyll (SPAD), Mann-Whitney U statistic: 774.0, p-value: 0.005669
Alerta de Chlorophyll (SPAD) - Semana -5
Date: 2024-07-30 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 21.0, p-value: 0.278632
Date: 2024-08-06 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 107.0, p-value: 0.439746
Date: 2024-08-14 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 137.0, p-value: 0.748676
Date: 2024-08-21 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 129.0, p-value: 0.984965
Date: 2024-08-27 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 30.0, p-value: 0.874735
Date: 2024-08-28 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 115.0, p-value: 0.637530
Date: 2024-09-04 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 85.5, p-value: 0.113370
Date: 2024-09-11 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 152.5, p-value: 1.000000
Date: 2024-09-17 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 38.0, p-value: 0.885024
Date: 2024-09-25 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 64.0, p-value: 0.843570
Date: 2024-10-02 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 965.0, p-value: 0.171597
Date: 2024-10-09 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 1486.0, p-value: 0.007788
ALERTA: Sap Ca (ppm)
Date: 2024-10-16 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 1539.0, p-value: 0.004622
Date: 2024-10-23 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 1369.5, p-value: 0.111799
Date: 2024-10-30 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 1367.0, p-value: 0.115999
Date: 2024-11-06 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 1365.0, p-value: 0.119435
Date: 2024-11-13 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 1165.0, p-value: 0.927019
Date: 2024-11-20 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 1119.0, p-value: 0.811760
Date: 2024-11-27 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 1087.0, p-value: 0.636468
Date: 2024-12-04 00:00:00, Variable: Sap Ca (ppm), Mann-Whitney U statistic: 712.0, p-value: 0.001279
Alerta de Sap Ca (ppm) - Semana 1
Date: 2024-07-30 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 27.0, p-value: 0.645377
Date: 2024-08-06 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 73.0, p-value: 0.039953
ALERTA: Sap NO3 (ppm)
Date: 2024-08-14 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 54.0, p-value: 0.005603
Date: 2024-08-21 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 77.0, p-value: 0.056798
Date: 2024-08-27 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 32.5, p-value: 1.000000
Date: 2024-08-28 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 89.0, p-value: 0.146736
Date: 2024-09-04 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 76.5, p-value: 0.054301
Date: 2024-09-11 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 86.5, p-value: 0.029336
Date: 2024-09-17 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 23.5, p-value: 0.245592
Date: 2024-09-25 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 58.0, p-value: 0.895220
Date: 2024-10-02 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 949.0, p-value: 0.137699
Date: 2024-10-09 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 880.0, p-value: 0.065416
Date: 2024-10-16 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 936.0, p-value: 0.114307
Date: 2024-10-23 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 1207.5, p-value: 0.686924
Date: 2024-10-30 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 1082.0, p-value: 0.610547
Date: 2024-11-06 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 1052.0, p-value: 0.465936
Date: 2024-11-13 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 1121.0, p-value: 0.823148
Date: 2024-11-20 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 1155.5, p-value: 0.982461
Date: 2024-11-27 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 1149.0, p-value: 0.985384
Date: 2024-12-04 00:00:00, Variable: Sap NO3 (ppm), Mann-Whitney U statistic: 1253.0, p-value: 0.461435
Alerta de Sap NO3 (ppm) - Semana -9
Date: 2024-07-30 00:00:00, Variable: 7in1_S_Temperature(C), Mann-Whitney U statistic: 22.5, p-value: 0.333666
Date: 2024-08-06 00:00:00, Variable: 7in1_S_Temperature(C), Mann-Whitney U statistic: 138.5, p-value: 0.703153
Date: 2024-08-14 00:00:00, Variable: 7in1_S_Temperature(C), Mann-Whitney U statistic: 123.0, p-value: 0.864734
Date: 2024-08-21 00:00:00, Variable: 7in1_S_Temperature(C), Mann-Whitney U statistic: 94.5, p-value: 0.212125
Date: 2024-08-27 00:00:00, Variable: 7in1_S_Temperature(C), Mann-Whitney U statistic: 45.0, p-value: 0.194872
Date: 2024-08-28 00:00:00, Variable: 7in1_S_Temperature(C), Mann-Whitney U statistic: 141.5, p-value: 0.622309
Date: 2024-09-04 00:00:00, Variable: 7in1_S_Temperature(C), Mann-Whitney U statistic: 170.0, p-value: 0.116449
Date: 2024-09-11 00:00:00, Variable: 7in1_S_Temperature(C), Mann-Whitney U statistic: 190.5, p-value: 0.218108
Date: 2024-09-17 00:00:00, Variable: 7in1_S_Temperature(C), Mann-Whitney U statistic: 37.0, p-value: 0.962567
Date: 2024-09-25 00:00:00, Variable: 7in1_S_Temperature(C), Mann-Whitney U statistic: 80.5, p-value: 0.191235
Date: 2024-10-02 00:00:00, Variable: 7in1_S_Temperature(C), Mann-Whitney U statistic: 1634.5, p-value: 0.000408
ALERTA: 7in1_S_Temperature(C)
Date: 2024-10-09 00:00:00, Variable: 7in1_S_Temperature(C), Mann-Whitney U statistic: 1610.5, p-value: 0.000333
Date: 2024-10-16 00:00:00, Variable: 7in1_S_Temperature(C), Mann-Whitney U statistic: 1677.5, p-value: 0.000119
Date: 2024-10-23 00:00:00, Variable: 7in1_S_Temperature(C), Mann-Whitney U statistic: 1450.0, p-value: 0.029179
Date: 2024-10-30 00:00:00, Variable: 7in1_S_Temperature(C), Mann-Whitney U statistic: 1436.5, p-value: 0.036816
Date: 2024-11-06 00:00:00, Variable: 7in1_S_Temperature(C), Mann-Whitney U statistic: 1482.5, p-value: 0.015578
Date: 2024-11-13 00:00:00, Variable: 7in1_S_Temperature(C), Mann-Whitney U statistic: 1545.5, p-value: 0.003975
Date: 2024-11-20 00:00:00, Variable: 7in1_S_Temperature(C), Mann-Whitney U statistic: 1446.5, p-value: 0.031119
Date: 2024-11-27 00:00:00, Variable: 7in1_S_Temperature(C), Mann-Whitney U statistic: 1452.5, p-value: 0.027870
Date: 2024-12-04 00:00:00, Variable: 7in1_S_Temperature(C), Mann-Whitney U statistic: 1575.5, p-value: 0.001931
Alerta de 7in1_S_Temperature(C) - Semana 0
Date: 2024-07-30 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 33.0, p-value: 0.959130
Date: 2024-08-06 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 134.0, p-value: 0.835784
Date: 2024-08-14 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 158.0, p-value: 0.266214
Date: 2024-08-21 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 117.0, p-value: 0.692302
Date: 2024-08-27 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 47.0, p-value: 0.130381
Date: 2024-08-28 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 143.0, p-value: 0.584730
Date: 2024-09-04 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 111.0, p-value: 0.534029
Date: 2024-09-11 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 149.0, p-value: 0.908035
Date: 2024-09-17 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 32.0, p-value: 0.742986
Date: 2024-09-25 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 61.0, p-value: 1.000000
Date: 2024-10-02 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 1024.0, p-value: 0.349875
Date: 2024-10-09 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 1192.0, p-value: 0.636438
Date: 2024-10-16 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 1239.5, p-value: 0.523784
Date: 2024-10-23 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 1344.0, p-value: 0.160539
Date: 2024-10-30 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 1615.0, p-value: 0.000701
ALERTA: Sap Conductivity (mS/cm)
Date: 2024-11-06 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 1573.0, p-value: 0.002061
Date: 2024-11-13 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 1332.0, p-value: 0.188403
Date: 2024-11-20 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 1195.0, p-value: 0.755472
Date: 2024-11-27 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 1387.0, p-value: 0.085729
Date: 2024-12-04 00:00:00, Variable: Sap Conductivity (mS/cm), Mann-Whitney U statistic: 1187.0, p-value: 0.800412
Alerta de Sap Conductivity (mS/cm) - Semana 4
Date: 2024-07-30 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 45.0, p-value: 0.194872
Date: 2024-08-06 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 133.0, p-value: 0.865300
Date: 2024-08-14 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 114.0, p-value: 0.610827
Date: 2024-08-21 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 93.0, p-value: 0.193509
Date: 2024-08-27 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 37.5, p-value: 0.599242
Date: 2024-08-28 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 158.0, p-value: 0.266083
Date: 2024-09-04 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 94.5, p-value: 0.213513
Date: 2024-09-11 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 226.0, p-value: 0.016710
ALERTA: Soil Ca Horiba (ppm)
Date: 2024-09-17 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 23.0, p-value: 0.235870
Date: 2024-09-25 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 69.0, p-value: 0.599361
Date: 2024-10-02 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 1149.0, p-value: 0.985379
Date: 2024-10-09 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 1338.0, p-value: 0.118872
Date: 2024-10-16 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 1442.5, p-value: 0.033580
Date: 2024-10-23 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 1420.5, p-value: 0.049547
Date: 2024-10-30 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 1610.5, p-value: 0.000789
Date: 2024-11-06 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 1515.5, p-value: 0.007814
Date: 2024-11-13 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 1637.5, p-value: 0.000379
Date: 2024-11-20 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 1404.5, p-value: 0.064799
Date: 2024-11-27 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 1531.5, p-value: 0.005481
Date: 2024-12-04 00:00:00, Variable: Soil Ca Horiba (ppm), Mann-Whitney U statistic: 1451.5, p-value: 0.028439
Alerta de Soil Ca Horiba (ppm) - Semana -3
Date: 2024-07-30 00:00:00, Variable: Air_sensor_Humidity(%RH), Mann-Whitney U statistic: 28.5, p-value: 0.752361
Date: 2024-08-06 00:00:00, Variable: Air_sensor_Humidity(%RH), Mann-Whitney U statistic: 103.0, p-value: 0.355722
Date: 2024-08-14 00:00:00, Variable: Air_sensor_Humidity(%RH), Mann-Whitney U statistic: 145.0, p-value: 0.533954
Date: 2024-08-21 00:00:00, Variable: Air_sensor_Humidity(%RH), Mann-Whitney U statistic: 153.5, p-value: 0.345946
Date: 2024-08-27 00:00:00, Variable: Air_sensor_Humidity(%RH), Mann-Whitney U statistic: 30.0, p-value: 0.878477
Date: 2024-08-28 00:00:00, Variable: Air_sensor_Humidity(%RH), Mann-Whitney U statistic: 107.0, p-value: 0.439578
Date: 2024-09-04 00:00:00, Variable: Air_sensor_Humidity(%RH), Mann-Whitney U statistic: 80.0, p-value: 0.073286
Date: 2024-09-11 00:00:00, Variable: Air_sensor_Humidity(%RH), Mann-Whitney U statistic: 153.0, p-value: 1.000000
Date: 2024-09-17 00:00:00, Variable: Air_sensor_Humidity(%RH), Mann-Whitney U statistic: 39.0, p-value: 0.814809
Date: 2024-09-25 00:00:00, Variable: Air_sensor_Humidity(%RH), Mann-Whitney U statistic: 47.5, p-value: 0.411621
Date: 2024-10-02 00:00:00, Variable: Air_sensor_Humidity(%RH), Mann-Whitney U statistic: 898.0, p-value: 0.063131
Date: 2024-10-09 00:00:00, Variable: Air_sensor_Humidity(%RH), Mann-Whitney U statistic: 813.0, p-value: 0.019227
ALERTA: Air_sensor_Humidity(%RH)
Date: 2024-10-16 00:00:00, Variable: Air_sensor_Humidity(%RH), Mann-Whitney U statistic: 783.5, p-value: 0.007005
Date: 2024-10-23 00:00:00, Variable: Air_sensor_Humidity(%RH), Mann-Whitney U statistic: 1044.5, p-value: 0.432987
Date: 2024-10-30 00:00:00, Variable: Air_sensor_Humidity(%RH), Mann-Whitney U statistic: 879.5, p-value: 0.046238
Date: 2024-11-06 00:00:00, Variable: Air_sensor_Humidity(%RH), Mann-Whitney U statistic: 887.0, p-value: 0.052602
Date: 2024-11-13 00:00:00, Variable: Air_sensor_Humidity(%RH), Mann-Whitney U statistic: 747.5, p-value: 0.003072
Date: 2024-11-20 00:00:00, Variable: Air_sensor_Humidity(%RH), Mann-Whitney U statistic: 1030.5, p-value: 0.375256
Date: 2024-11-27 00:00:00, Variable: Air_sensor_Humidity(%RH), Mann-Whitney U statistic: 936.0, p-value: 0.114301
Date: 2024-12-04 00:00:00, Variable: Air_sensor_Humidity(%RH), Mann-Whitney U statistic: 758.5, p-value: 0.003978
Alerta de Air_sensor_Humidity(%RH) - Semana 1

       Fecha        Variable  U_statistic   p_value  n_group1  n_group2
0 2024-07-30  Soil pH Horiba         42.0  0.292162         8         8
1 2024-08-06  Soil pH Horiba         91.5  0.174132        16        16
2 2024-08-14  Soil pH Horiba        142.0  0.610532        16        16
3 2024-08-21  Soil pH Horiba        130.5  0.939815        16        16
4 2024-08-27  Soil pH Horiba         40.0  0.441803         8         8